### ISSUE TITLE
java:s4143 not found in sonarqube 7.9.4

### ISSUE THREAD

**Issue by maybeec** [devonfw/sonar-devon4j-plugin#111]
### Expected behavior

As an architect, I want to install devon4j sonar plugin so that I can verify my architecture.

### Actual behavior

After installing the latest sonar-devon4j-plugin from marketplace in sonarqube 7.9.4, I get the following blocking error on startup:
```
java.lang.IllegalStateException: Rule with key 'java:S4143' not found
	at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
	at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.lambda$updateOrCreateBuilder$6(BuiltInQProfileRepositoryImpl.java:200)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Unknown Source)
	at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.updateOrCreateBuilder(BuiltInQProfileRepositoryImpl.java:197)
	at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.lambda$toQualityProfileBuilders$5(BuiltInQProfileRepositoryImpl.java:176)
	at java.base/java.util.HashMap.compute(Unknown Source)
	at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.toQualityProfileBuilders(BuiltInQProfileRepositoryImpl.java:174)
	at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.lambda$toFlatList$2(BuiltInQProfileRepositoryImpl.java:132)
	at org.sonar.core.util.stream.MoreCollectors.lambda$uniqueIndex$9(MoreCollectors.java:258)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.toFlatList(BuiltInQProfileRepositoryImpl.java:130)
	at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.initialize(BuiltInQProfileRepositoryImpl.java:84)
	at org.sonar.server.qualityprofile.BuiltInQProfileLoader.start(BuiltInQProfileLoader.java:37)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:48)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:85)
	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:46)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:82)
	at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:196)
	at org.sonar.server.platform.Platform.access$400(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$1(Platform.java:121)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:121)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Install the plugin
2. Restart sonarqube

### Comments/Hints:

Further installed plugins:
![image](https://user-images.githubusercontent.com/1427255/97530626-d0a0bc00-19b2-11eb-9009-75dc987db861.png)

### Affected version:

* OS: https://hub.docker.com/layers/porscheinformatik/sonarqube/7/images/sha256-bfdf28646a7bac05b0f05054d39147095b79de921c13e6b82427f68dfa8c62d7?context=explore

**Comment by lmarniazman** [comment]
Thanks for finding this bug.
It seems that this rule can not be found in versions 7.9.4, 8.0 and 8.1, which is weird since this rule S4143 exists since July 2017, so long before any of these versions were released.

**Comment by lmarniazman** [comment]
This is an issue related to the version of SonarJava that is installed on the server. Not all rules that we are using are available in all versions of SonarJava. 

I am working on a fix for this right now, so that we can include / exclude certain rules by detecting which version of SonarJava is running on SonarQube.

**Comment by maybeec** [comment]
I am totally new to sonarqube plugin creations, but if you need a logic which will work in any environment, possibly you can enable any of the dependent rules just in case they are available at all? 
This would make the plugin much more stable although it will not be stable with respect to the rules executed.

**Comment by hohwille** [comment]
As we are adding the rules to our quality profile sequentially, we should simply check if that rule is actually available and otherwise only log a warning and continue. If no other way, we can simply catch the exception and proceed. Even better would be to check the existance of the rule without exception if possible.

**Comment by hohwille** [comment]
As discussed with @lmarniazman the exception is not raised, when we are looking up or adding the rule but deferred after our plugin bootstrapping is completed. Therefore we can not catch the error and handle the problem.
